name: 'Run TEAM Engine'

description: 'Spins up a TEAM Engine instance inside a docker container'

branding:
  icon: 'award'
  color: 'blue'

inputs:
  test-suite-identifier:
    description: 'Identifier of the Executable Test Suite (etscode) to be run. Example: ogcapi-features-1.0'
  test-session-arguments:
    description: >
      Space-separated string with arguments that are to be sent for running the test session. example:
      'iut=http://pygeoapi:5000'

outputs:
  test-results:
    description: 'Test results'
    value: '${{ steps.run-test-suite.outputs.test_results }}'

runs:
  using: 'composite'
  steps:
    - name: 'Add action path to the global path'
      shell: bash
      run: echo "${{ github.action_path }}" >> ${GITHUB_PATH}
    - name: 'Start TEAM engine'
      shell: 'bash'
      run: >
        docker run
        --detach
        --rm
        --name team-engine
        --publish 8081:8080
        --add-host=host.docker.internal:host-gateway
        ogccite/teamengine-production:1.0-SNAPSHOT'
    - name: 'Wait for TEAM engine to become usable'
      shell: 'bash'
      run: >
        docker exec team-engine
        bash -c 'curl --silent --output /dev/null --write-out "%{http_code}" localhost:8080/teamengine/'
    - name: 'Register test user in TEAM engine'
      shell: 'bash'
      run: register-test-user.sh
    - name: 'Run test suite'
      id: 'run-test-suite'
      env:
        INPUT_TEST_SUITE_IDENTIFIER: ${{ inputs.test-suite-identifier }}
        INPUT_TEST_SESSION_ARGUMENTS: ${{ inputs.test-session-arguments }}
      shell: bash
      run: run-test.sh