[tool.poetry]
name = "cite-runner"
version = "0.1.0"
description = ""
authors = ["Ricardo Garcia Silva <ricardo.garcia.silva@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "cite_runner", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.12.3"
httpx = "^0.27.0"
jinja2 = "^3.1.4"
jinja2-humanize-extension = "^0.4.0"
pydantic = "^2.10.4"
pydantic-settings = "^2.8.1"
lxml = "^5.3.1"
isodate = "^0.7.2"

[tool.poetry.scripts]
cite-runner = "cite_runner.main:app"

[tool.poetry.group.dev.dependencies]
ipython = "^8.31.0"
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
