name: Continuous Integration

on:
  push:  # will run both when pushing a branch and when pushing a tag

  pull_request:

env:
  COLUMNS: 120

jobs:
  run-ci:
    runs-on: ubuntu-24.04
    steps:
      - name: "Grab code"
        uses: actions/checkout@v4.2.2

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.13"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: "Install code"
        run: uv sync --frozen

      - name: "Run ruff linter"
        run: uv run ruff check

      - name: "Run ruff formatter"
        run: uv run ruff format --check

      - name: "Run tests"
        run: uv run pytest
