name: Continuous Integration

on:
  push:  # will run both when pushing a branch and when pushing a tag

  pull_request:

env:
  COLUMNS: 120

jobs:
  run-ci:
    runs-on: ubuntu-24.04
    steps:
      - name: grab code
        uses: actions/checkout@v4.2.2

      - name: install poetry
        run: pipx install poetry==2.1.1

      - name: setup Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: "3.10"
          cache: poetry

      - name: install code with dev dependencies
        run: poetry install --with ci

      - name: run ruff linter
        run: poetry run ruff check

      - name: run ruff formatter
        run: poetry run ruff format --check

      - name: run tests
        run: poetry run pytest
